# Generated by Django 4.2.17 on 2024-12-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
