# Generated by Django 4.2.17 on 2024-12-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='notification_count',
            field=models.IntegerField(default=0),
        ),
    ]
